### ISSUE TITLE
Raster fixer: clip rasters to DEM extent if extents differ

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#688] opened 2022-08-31 19:14 UTC
For full context see https://github.com/nens/ThreeDiToolbox/issues/574

Include checks: is the raster the same as the DEM in terms of:
- pixel size
- skew / rotation (should be 0)
- crs

*Inputs*
- Digital Elevation Model
- A list of other rasters

*Outputs*
- Preferably, rasters are edited in-place; otherwise, let users choose a postfix (e.g. '_fixed_extent')

*Algorithm*
- Clip rasters to DEM extent if extents differ

*Feedback*
- The python method should accept a feedback object to report progress (0-100) using `.setProgress()` and logging. Please check with @ldebek for details.

**Comment by caspervdw** [comment] 2022-11-03 09:55
Backend solution: https://github.com/nens/threedi-tables/pull/198 (this makes this ticket a duplicate of #689

**Closed as completed by caspervdw** 2022-11-03 09:55 UTC
Labels: duplicate
