### ISSUE TITLE
x-axis is always in ks

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#465] opened 2019-11-22 10:15 UTC
this is plainly annoying. no one uses that time scale.

Can we perhaps use something like this?
https://gist.github.com/iverasp/9349dffa42aeffb32e48a0868edfa32d

**Comment by leendertvanwolfswinkel** [comment] 2021-07-01 21:08
duplicate of issue #495

**Closed as completed by leendertvanwolfswinkel** 2021-07-01 21:08 UTC
Labels: duplicate, enhancement
