### ISSUE TITLE
[Bug]: Raster-checker initial wl raster errors

### ISSUE THREAD

**Issue by Overmeen** [nens/threedi-results-analysis#694] opened 2022-07-19 12:17 UTC
### Contact Details

stijn.overmeen@nelen-schuurmans.nl

### Complexity

moderate

### Priority

high prio

### What happened?

Raster-checker gives error when initial water level data / no-data differs from DEM. However, is allowed.

Especially important to fix with this new prominent place of the checkers in the Models and Simulations. Example of client who did not proceed to upload model due to these errors:
Ticket 2207 0152

### How to Reproduce?

Open calculater.
Press 1,
Press +,
Press 1,
Press =

### What did you expect and what was the actual result?

I expected 2 but the calculator returned 3

### Add screenshots, video's etc

The maximum size for files is 25MB and the maximum size for images is 10MB.

### Additional info

Anything else you would like to share?

**Comment by leendertvanwolfswinkel** [comment] 2022-09-12 18:44
Duplicate of #515

**Closed as not planned by leendertvanwolfswinkel** 2022-09-12 18:44 UTC
Labels: bug
