### ISSUE TITLE
Sideview tool is broken for qgis 3.16.6 and higher

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#561] opened 2021-06-28 14:42 UTC
When using qgis 3.16.6 and threeditoolbox version 1.19 or higher the sideview tool doesn't work.

The following reproduces the error"
- activate the sideview toolbar 
- choose sideview trajectory

A python error will be thrown:

`2021-06-28T16:12:03     WARNING    Traceback (most recent call last):
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 916, in canvasReleaseEvent
              self.callback_on_select(selected_points, transformed_point)
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 1699, in on_route_point_select
              self.active_sideview.set_sideprofile(self.route.path, self.route.path_points)
              File "C:\Users\jonas.vanschrojenste\AppData\Roaming\3Di\QGIS3\\profiles\default/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 258, in set_sideprofile
              begin_node = self.node_dict[begin_node_id]
             KeyError: '27265'`

Example data here:

https://drive.google.com/drive/folders/16tLQEmPwQEzghEvUuZiR8_AhCTiFLApT?usp=sharing

**Comment by leendertvanwolfswinkel** [comment] 2021-07-01 14:32
Issue has high priority because it is a blocker, i.e. makes the whole tool unusable. Other SideView-tool related issues are to be picked up later, after refactor of all results-related tools

**Comment by ldebek** [comment] 2021-07-08 14:05
@leendertvanwolfswinkel @Jonasvsl 
I did some tests on attached data using QGIS 3.16.8 with plugin version 1.19 and sideway trajecory works just fine for me. Could you add some more details to this ticket (like between each connection nodes it occurs)? We just have a short call so you can demonstrate exact workflow to reproduce this issue.

**Comment by leendertvanwolfswinkel** [comment] 2021-07-08 15:36
I tried with the same dataset as Jonas, and also ran into the issue. Screen capture here: https://drive.google.com/file/d/1tJ1lFTVmYu6EuWzdinUrDyaL6oqbvuDB/view?usp=sharing

3Di Toolbox version 1.19

QGIS version
3.16.7-Hannover
QGIS code revision
0471743889
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
edit3dischematisation; 
profiletool; 
ThreeDiCustomizations; 
ThreeDiToolbox; 
threedi_api_qgis_client; 
threedi_custom_stats; 
threedi_model_builder; 
valuetool; 
db_manager; 
MetaSearch; 
processing

**Comment by ldebek** [comment] 2021-07-09 14:37
PR with fix ready for review and testing.
https://github.com/nens/ThreeDiToolbox/pull/577

**Comment by leendertvanwolfswinkel** [comment] 2021-07-09 14:46
@Jonasvsl who is supposed to review this? Reinout?

**Comment by leendertvanwolfswinkel** [comment] 2021-07-13 18:04
I tried again with the same model, but run into a different error now. I started the sideview at connection node 3690, ending at 3789
```
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s) 
Traceback (most recent call last):
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox v1.20/python/plugins\ThreeDiToolbox\tool_sideview\sideview_view.py", line 818, in update_water_level_cache
    "s1", content_pk=node["id"], fill_value=np.NaN
  File "C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox v1.20/python/plugins\ThreeDiToolbox\datasource\threedi_results.py", line 197, in get_timeseries
    return np.hstack([timestamps, values])
  File "", line 6, in hstack
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\numpy\core\shape_base.py", line 346, in hstack
    return _nx.concatenate(arrs, 1)
  File "", line 6, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 3 dimension(s)
```

Python versie: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS versie: 3.16.4-Hannover Hannover, 654e76b3cb 

Python pad:
C:/OSGEO4~1/apps/qgis-ltr/./python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox v1.20/python
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox v1.20/python/plugins
C:/OSGEO4~1/apps/qgis-ltr/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\leendert.vanwolfswin\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32
C:\OSGEO4~1\apps\Python37\lib\site-packages\win32\lib
C:\OSGEO4~1\apps\Python37\lib\site-packages\Pythonwin
C:/Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox v1.20/python

**Comment by ldebek** [comment] 2021-07-14 10:32
@leendertvanwolfswinkel This is looking like a separate issue... and I cannot replicate it anyway as sideview tool works for me at those nodes as well...
![image](https://user-images.githubusercontent.com/11883222/125607809-5fea9b01-9c49-4110-ab8a-eecf3bc4eb7e.png)
Edit:
I've managed to reproduce this error after creating new QGIS profile. Fix is on the way.

**Comment by ldebek** [comment] 2021-07-14 11:45
@leendertvanwolfswinkel Fix for this issue is on master now. Feel free to give it a try again.

**Comment by leendertvanwolfswinkel** [comment] 2021-07-14 12:59
No more python errors, but the tool doesn't give a correct result unfortunately.

Still in the same model, if I draw a SideView from connection node 3467 to 3959, the result should look like this (3Di Toolbox 1.19 @ QGIS 3.16.4):

![image](https://user-images.githubusercontent.com/26224299/125628005-32dddb76-07a1-491b-b673-55924c521053.png)

Using the 3Di Toolbox that is currently on master, I get this:

![image](https://user-images.githubusercontent.com/26224299/125628392-822db64b-081d-4095-bf70-861ec36c00ad.png)
 
It seems that the pipe tops (invert level + height) are missing (except for the first pipe), so that the line connects the manhole surface levels directly.

**Comment by ldebek** [comment] 2021-07-14 15:48
@leendertvanwolfswinkel Fix for the issue above is on master now. Hopefully this time it will be fixed for good. :)

**Comment by leendertvanwolfswinkel** [comment] 2021-07-15 10:49
Works properly now, well done @ldebek

**Closed as completed by leendertvanwolfswinkel** 2021-07-15 10:49 UTC
Labels: bug, urgent
