### ISSUE TITLE
Installing 3Di Toolbox fails in QGIS 3.22 due to h5py not being available for python 3.9

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#584] opened 2021-07-23 06:35 UTC
How to reproduce:

Install QGIS 3.16.8
Create a new user profile
Add https://plugins.3di.live/plugins.xml as a plugin repository
Install 3Di Toolbox

I get the following error:

```
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "C:\PROGRA~1/QGIS31~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\__init__.py", line 26, in 
    dependencies.ensure_everything_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\dependencies.py", line 85, in ensure_everything_installed
    _ensure_h5py_installed()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\dependencies.py", line 125, in _ensure_h5py_installed
    hdf5_version = _get_hdf5_version()
  File "C:\Users/leendert.vanwolfswin/AppData/Roaming/QGIS/QGIS3\profiles\3Di Toolbox 1.20/python/plugins\ThreeDiToolbox\dependencies.py", line 375, in _get_hdf5_version
    process = subprocess.Popen(
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by leendertvanwolfswinkel** [comment] 2021-07-23 06:37
@ldebek please look into this a.s.a.p.

**Comment by ldebek** [comment] 2021-07-23 08:32
This doesn't occur on my machine, but from error message I can tell that it comes from QGIS which is using Python 3.9, so dependncies will fail as some of the binaries are python 3.7 only.

**Comment by leendertvanwolfswinkel** [comment] 2021-07-23 08:39
@ldebek How complex would it be to fix this?

@Jonasvsl  If not fixed short term, we should warn users in our docs that they cant use qgis > 3.16.6

**Comment by reinout** [comment] 2021-07-23 09:19
The problem is not python3.7/3.9, I think, but a missing `h5stat.exe`.

Half a year ago, there apparently was a problem with h5py versions, if I read the docstring for `_ensure_h5py_installed()` correctly:
https://github.com/nens/ThreeDiToolbox/blob/master/dependencies.py#L90-L107

This calls (only on windows) ` _get_hdf5_version()`:

https://github.com/nens/ThreeDiToolbox/blob/master/dependencies.py#L374-L384

... and this one calls `h5stat.exe --version` on the commandline. Which leads to the "file not found" error in this issue and in #575 (and I thought there was another one).

Some suggestions:

- Add a try/except around it and ignore the check if missing?
- Investigate why it is missing?
- Perhaps most productive: **check if the version check is still needed**.

**Comment by ldebek** [comment] 2021-07-23 10:06
@reinout That would make sense - beside the fact that it's working fine on my QGIS 3.16.8 on Win 10 with Python 3.7 (fresh install via OSGeo4W). Only obvious difference that I can see there is a Python (3.7 vs 3.9) version. Of course I can add some checks that you suggest, but I'm not sure if that will be sufficient.

**Comment by reinout** [comment] 2021-07-23 10:20
The docstring for `_ensure_h5py_installed()` says the check is done because of a problem/change in qgis **3.10**. So my *guess* is that the custom h5py check is no longer needed.
OTOH, Richard added the code only half a year ago, so it might still be relevant.

----

@ldebek and @leendertvanwolfswinkel : you have different results for (apparently) the same qgis version: perhaps double-check each other's installation method and OS version? Especially the fact that Leendert has python 3.9.... I would not expect qgis to change such a "detail" in a long term support version.

**Comment by ldebek** [comment] 2021-08-03 08:57
After testing it turned out that there are 2 versions of QGIS and OSGeo4W installers available on QGIS download page. There is a new one based on Python 3.9 (which is not supported by the plugin) and second is using Python 3.7 with old dependencies. OSGeo4W network installer with Python 3.9 brings new versions of some dependencies (H5Py, SciPy etc.) while standalone QGIS 3.16.9 LTR installer doesn't have HDF5 binaries included yet at all. Because of that I would recommend to support only QGIS 3.16.9 LTR build based on Python 3.7 and update dependencies when next QGIS 3.22 LTR will be released. This will be based on Python 3.9 from the beginning, so dependencies update should be much easier and cleaner. QGIS 3.16.9 LTR with Python 3.7 is available on main QGIS download page.

![image](https://user-images.githubusercontent.com/11883222/127987444-a305f28d-4a40-4b8b-8bf1-11e44ed616cc.png)

**Comment by leendertvanwolfswinkel** [comment] 2021-08-05 20:22
@ ldebek I agree

@lisannewapstra we can tell customers that contact the service desk with this issue that they should download the 3Di Modeller Interface installer, or, if they really want to use QGIS and install the 3Di plugins separately, use the LTR from the 'old OSGeo4W' section on the download website.

**Comment by lisannewapstra** [comment] 2021-08-06 14:39
Hi Leendert and Lukasz,
That sounds good, thanks!

**Comment by Patrick-Nijman** [comment] 2021-08-30 11:13
I would recommend to put the proper installers next to the download link in the documentation. Or directly on the website. Ideally. Create a all-in-one installer. See following snippet taken from https://docs.3di.live/d_before_you_begin.html#plugin-installation

![image](https://user-images.githubusercontent.com/86961942/131330836-21329add-c9db-4ea3-8d80-f5d625433fc9.png)

**Closed as completed** 2022-04-25 11:44 UTC
Labels: bug, high prio, Topdesk
