### ISSUE TITLE
coordinates for sufhyd are switched in QGIS 3.10 compared to QGIS 3.4

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#509] opened 2020-10-16 11:54 UTC
the following was tested usqing qgis 3.10 and threeditoolbox 1.14

hmmm. You're right. I tried another sufhyd (didactisch.hyd) which to me looks similar and that also ended up in the african sea.

I added a column to the strijen sqlite (based on an empty.sqlite) and I do see the right coordinates:

![image](https://user-images.githubusercontent.com/1453159/96255363-16bf4e00-0fb7-11eb-8971-fd765d2317e6.png)

switching the lat lon (I used googlemaps):

Capture (3).PNG
![image](https://user-images.githubusercontent.com/1453159/96255376-1cb52f00-0fb7-11eb-9738-7a5d24cb598b.png)

and that is exactly where the data ended up. So the xy coordinates are switched.

did the same test under QGIS 3.4
and then didactisch.hyd is on the right spot.
it appears there is a difference between qgis 3.10 and 3.4 

![image](https://user-images.githubusercontent.com/1453159/96255389-22127980-0fb7-11eb-8803-6532f377694a.png)

threeditoolbox version in both cases is 1.14

**Comment by Jonasvsl** [comment] 2020-10-16 11:57
testdata. it should end up somewhere in rijswijk
[didactisch (1).zip](https://github.com/nens/ThreeDiToolbox/files/5391316/didactisch.1.zip)

**Comment by leendertvanwolfswinkel** [comment] 2021-01-25 12:37
This is caused by breaking changes from GDAL 2.x to 3.0. From the gdal migration guide github.com/OSGeo/gdal/blob/master/gdal/MIGRATION_GUIDE.TXT:

MIGRATION GUIDE FROM GDAL 2.4 to GDAL 3.0
-----------------------------------------
[...]
- Substantial changes, sometimes backward incompatible, in coordinate reference
  system and coordinate transformations have been introduced per
  https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn
    * OSRImportFromEPSG() takes into account official axis order.
      Traditional GIS-friendly axis order can be restored with
      OGRSpatialReference::SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);

[...]

I assume this can be fixed by adding the lines below to ThreeDiToolbox\tool_commands\import_sufhyd\import_sufhyd_main.py on line 34. Haven't tested for import SUFHYD, but works for import GWSW HydX

```
    if int(gdal.__version__[0]) >= 3:
        source_crs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
        dest_crs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
```

**Comment by RichardB9** [comment] 2021-02-11 15:26
I am not able to reproduce this bug.
Using Qgis 3.10.14 compiled with different version of gdal/pyproj:
1. Gdal = 3.1.4 and pyproj = 2.6.1.post
2. Gdal = 2.2.3 and pyproj = 1.9.5.1

Both give the same results, with the results ending somewhere near Rijswijk

**Comment by Jonasvsl** [comment] 2021-02-11 15:45
and you're using an empty.sqlite right?

**Comment by Jonasvsl** [comment] 2021-02-12 08:41
it is weird. with this setup I still end up in the ocean:

QGIS version
3.16.1-Hannover
QGIS code revision
b381a90dca
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
ThreeDiToolbox; 
db_manager; 
MetaSearch; 
processing; 
profiletool; 
threedi_api_qgis_client

**Closed as completed** 2021-03-04 13:19 UTC
Labels: bug
