### ISSUE TITLE
windows display settings messes up the graphs in the modeller interface

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#590] opened 2021-09-10 06:45 UTC
it appears that when a user has two displays

one display at 100%
and one display at 125 % (windows default)

And drags the graphs from one display to another, the graphs mess up

please investigate what combinations cause this issue. it does not throw an error but it gives users a false value in the graph.

might be related to this issue: https://github.com/pyqtgraph/pyqtgraph/issues/756

![image](https://user-images.githubusercontent.com/1453159/132811368-e5d62ef5-a007-4835-b00d-003a163855f7.png)

This however messes up the graphs in the 3Di toolbox. It is clearly seen that there is something wrong with the y-axis, but for users it is a puzzle what is wrong. 

Can we check windows display settings and scaling and issue a warning to the user if these are not set to 100%?

100% Image

![image-_1_](https://user-images.githubusercontent.com/86961942/168076860-78ea1c7d-e944-4050-b9b1-ffe7bd265b00.jpg)

120% Image

![image](https://user-images.githubusercontent.com/86961942/168076848-d55b9720-aadd-4aa7-90c4-522875b0905b.jpg)

(See this topdesk ticket: 2106 0200 issue with windows zoom settings)

**Comment by leendertvanwolfswinkel** [comment] 2022-05-25 08:57
Closing because it is more or less a duplicate of #563

**Closed as completed by leendertvanwolfswinkel** 2022-05-25 08:57 UTC
Labels: Topdesk
