### ISSUE TITLE
Statistics tool: KeyError

### ISSUE THREAD

**Issue by Jonasvsl** [nens/threedi-results-analysis#663] opened 2022-07-05 07:48 UTC
### Complexity

moderate

### Priority

high prio

### What happened?

clicked on the icon for statistics. failed with pytrhon error

### How to Reproduce?

open de sqlite with the 3Di toolbox
add the results from the sim
click on the statistics icon

### What did you expect and what was the actual result?

i did not expect an error. 

### Add screenshots, video's etc

![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/1453159/177277069-c5bd8827-373c-4ddc-af9b-509b4d5a0b35.png)

### Relevant log output

```shell
2022-07-05T08:53:48     WARNING    ThreeDiToolbox.tool_statistics.tools.statistics
             no result for pipe with spatialite id 15
```

### Additional info

I used these versions:
MI 3.22
M&S 3.1
SE 1.1.1.
3DiT 2.2

**Comment by leendertvanwolfswinkel** [comment] 2022-07-05 19:04
Closing because the issue is too vague to reproduce properly. Will hopefully be fixed with #598

**Closed as completed by leendertvanwolfswinkel** 2022-07-05 19:04 UTC
Labels: bug, can't reproduce
