### ISSUE TITLE
Raster fixer: equal pixel size as DEM

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-results-analysis#687] opened 2022-08-31 19:10 UTC
For full context see https://github.com/nens/ThreeDiToolbox/issues/574

*Inputs*
- Digital Elevation Model
- A list of other rasters

*Outputs*
- Preferably, rasters are edited in-place; otherwise, let users choose a postfix (e.g. '_fixed_pixel_size')

*Algorithm*
- Warp rasters that have different pixel size than the DEM to make the pixel size the same (and skew 0)
- Use nearest neighbour interpolation
- Output raster should have the same offset as the DEM, so that the pixels are exactly on top of one another

*Feedback*
- The python method should accept a feedback object to report progress (0-100) using `.setProgress()` and logging. Please check with @ldebek for details.

**Comment by caspervdw** [comment] 2022-11-03 09:55
Backend solution: https://github.com/nens/threedi-tables/pull/198 (this makes this ticket a duplicate of https://github.com/nens/ThreeDiToolbox/issues/689)

**Closed as completed by caspervdw** 2022-11-03 09:55 UTC
Labels: duplicate
